### ISSUE TITLE
support Date conversions and not just DateTimes

### ISSUE THREAD

**Issue by idlehands** [Shimmur/checker_cab#24]
we missing converting iso8601 date string. we should support them, too.

**Comment by JwillR** [comment]
I'm happy to write this feature.

**Comment by JwillR** [comment]
It appears to be already done. 

I found the [code that supports it here](https://github.com/Shimmur/checker_cab/blob/a322a5d1ca7b75d7d007c2731921810944a44583/lib/checker_cab.ex#L250-L252), and [the accompanying test
](https://github.com/Shimmur/checker_cab/blob/a322a5d1ca7b75d7d007c2731921810944a44583/test/checker_cab_test.exs#L284-L286)

This issue looks ready to be closed. Is there anything else that should happen with this feature?
