### ISSUE TITLE
Fix typo in test output.

### ISSUE THREAD

**Issue by GeoffreyPS** [Shimmur/checker_cab#33]
We have an issue with the main error message: 
```elixir
  defp error_message_for(missing, mismatched) do
    ["There were issues the comparison:", error_message_for_missing(missing), error_message_for_mismatched(mismatched)]
    |> Enum.reject(&(&1 == ""))
    |> Enum.join("\n\n")
  end
```

[See the file here](https://github.com/Shimmur/checker_cab/blob/4a62ccbd07d103cc9967428f53b260e0bd2a2f26/lib/checker_cab.ex#L182)

The error string should read _"There were issues with the comparison:"_

**Comment by JwillR** [comment]
PR #25 should take care of this.
